language: cpp
dist: bionic
compiler:
  - clang
os:
  - linux
env:
  global:
   - secure: "dV4afOeNl9/wBLRaIzqBD0NoNDP66qcsyAl7KH8fo4eH2HGdxV6sDX2EKcW44l7fJH6pS3qKX1ZDREnIyjWs9Ktms/F1oSe9unF1CH84DeIWkDHwpIEccEQ66i5DfTlZbmeo2Bp2qnRnMuS/9uSHvnmHOG29rh0rjnPGXcRX4KMYXShwmlv5y6tdvCfa9BoUaQnaQx9VUP/uXiqczS73BBzX5PAn0VV7B3X31i3AB90SWY0PmQDOM7zWkH9w8fd9kNo+sINAScfgEDV2yAwvrdFx/D4VRVecEi4W/O00xZGcDy2Sib81lz2m0pMmMBLp/ewT9N8erDfWH1pls9eN5gtCoSTn5pVxgTGZW2tr821YKaIiySFbgjL4nwGa6Rjsu7n94LTHZ/haReSnk5wKxvI2dwXSsS+rVA+0cqzWGZ1l4z+780f38nM58Yg3vSs8OKQpUnFjV0ZaN5sGnDCiccpp6lvidDbd3rNZff7putuK+qw//xQShEYqFnRUcuz4ZFx8U8CcOVvY3eNlZrqv44I/9UeHDQwEvD/XRz/QfYsdJWDPvWu8KAmD4QIqNSurDJLVRoQp40BH/vrpB8zOzEcynsriclqj5pJyEUdk0KYeCP1Pw8S6sWjfkmPzmyDjZCY9e/m2mF+p+WaQc3VkpayIBmBpLBIMh7uIm4VHP+A="

before_install:
  - sudo apt-get update
  - sudo apt-get install pv
script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then travis_wait 30 ./tests/scripts/ci-script-travis.sh | pv -q -L 3k; fi'
